### ISSUE TITLE
minor typo in readme.md

### ISSUE THREAD

**Issue by slootsky** [ldotlopez/ha-historical-sensor#11]
there is an extra T at the end of   

home_assistant_histocial_sensort

and historical is spelled wrong in that as well

Thanks for this module - it look like it is exactly what I need to backfill data from a travelling sensor

**Comment by ldotlopez** [comment]
I missed this issue!

> Thanks for this module - it look like it is exactly what I need to backfill data from a travelling sensor

:heart:
